"""Seguimiento inicial

Revision ID: 17b354793e5a
Revises:
Create Date: 2026-01-18 18:41:00.287867

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "17b354793e5a"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
