"""add address to user

Revision ID: c92ee9ddb5e6
Revises: 17b354793e5a
Create Date: 2026-01-18 18:43:41.546589

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c92ee9ddb5e6"
down_revision: Union[str, Sequence[str], None] = "17b354793e5a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("address", sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "address")
    # ### end Alembic commands ###
