"""añadir cantidad a items de orden

Revision ID: 4bd5e3bb47a3
Revises: 59b795bacaf1
Create Date: 2026-01-19 14:02:44.273163

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4bd5e3bb47a3"
down_revision: Union[str, Sequence[str], None] = "59b795bacaf1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("order_items", schema=None) as batch_op:
        batch_op.add_column(sa.Column("quantity", sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("order_items", schema=None) as batch_op:
        batch_op.drop_column("quantity")

    # ### end Alembic commands ###
