"""Eliminar items en cascada y estatus en Order

Revision ID: 521438489058
Revises: 4bd5e3bb47a3
Create Date: 2026-01-20 11:28:16.661876

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "521438489058"
down_revision: Union[str, Sequence[str], None] = "4bd5e3bb47a3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "status",
                sa.String(length=10),
                server_default=sa.text("'Pendiente'"),
                nullable=False,
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.drop_column("status")

    # ### end Alembic commands ###
